name: bruno
version: 1.0.0
homepage: https://github.com/LianjiaTech/bruno
description: An enterprise-class package of Flutter components for mobile applications.
environment: 
  sdk: '>=2.15.0 <4.0.0'

dependencies: 
  xml: 5.3.1
  lpinyin: ^2.0.3
  path_drawing: 1.0.0
  flutter_easyrefresh: ^2.1.1
  intl: ^0.17.0
  photo_view: ^0.13.0
  provider: ^6.0.5
  badges: ^3.1.1
  expand_tap_area: 1.1.0
  get: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/icons/radio/
    - assets/images/no_data.png
    - assets/images/two_line_bubble.png
    - assets/json/
    - assets/json/china.json
  fonts: 
    - family: Condensed
      fonts: 
        - asset: assets/fonts/DINCondensed-Bold.ttf

